refactor bash scripts, replace Makefile with justfile

diff --git a/src/bin/config/ele-config b/src/bin/config/ele-config
--- a/src/bin/config/ele-config
+++ b/src/bin/config/ele-config
@@ -1,33 +1,53 @@
-#!/bin/bash
+#!/usr/bin/env bash
+#
+# Description: This script is used to read the configuration file for the ele-cli tool. It can display the entire configuration or a specific value based on a provided YAML path.
+# Usage: ele-config [options]
+#
+
+set -Eeuo pipefail
 
 usage() {
-  echo "Usage: $(basename "$0") [-h] [yaml_path]"
+	echo "Usage: $(basename "$0") [-h] [yaml_path]"
 }
+
+die() {
+	echo.error "$*" >&2
+	exit 1
+}
+
 while getopts "h" arg; do
-  case $arg in
-  h)
-    usage
-    exit 0
-    ;;
-  *)
-    usage
-    exit 1
-    ;;
-  esac
+	case $arg in
+	h)
+		usage
+		exit 0
+		;;
+	*)
+		usage
+		exit 1
+		;;
+	esac
 done
 shift $((OPTIND - 1))
-if [[ $# -ne 0 ]] && [[ $# -ne 1 ]]; then
-  usage
-  exit 0
+
+if [[ $# -gt 1 ]]; then
+	usage
+	exit 1
 fi
 
-readonly config_file="$HOME/.ele/config.yaml"
+if ! command -v yq &>/dev/null; then
+	die "yq is not installed"
+fi
+
+readonly config_file="${HOME}/.ele/config.yaml"
+
+if [[ ! -f $config_file ]]; then
+	die "Configuration file not found: $config_file"
+fi
+
+if [[ $# -eq 0 ]]; then
+	yq '.' "$config_file"
+	exit 0
+fi
+
 readonly yaml_path=$1
-
-if [[ -f "$config_file" ]]; then
-  if [[ $# -eq 0 ]]; then
-    yq "$config_file"
-  elif [[ $# -eq 1 ]]; then
-    yq "$yaml_path"' // ""' "$config_file"
-  fi
-fi
+yq -r "${yaml_path} // \"\"" "$config_file"
