add ele-init (#33)
* update ele-logs message on compose file not found
* add ele-init

diff --git a/src/bin/operations/ele-init b/src/bin/operations/ele-init
--- a/src/bin/operations/ele-init
+++ b/src/bin/operations/ele-init
@@ -1,19 +1,14 @@
 #!/usr/bin/env bash
 
 usage() {
-	echo "Usage: $(basename "$0") [-h] [-f] composeName"
+	echo "Usage: $(basename "$0") [-h] composeName..."
 	echo " -h show this help"
-	echo " -f  follow logs"
 }
-log_options=()
-while getopts "hf" arg; do
+while getopts "h" arg; do
 	case $arg in
 	h)
 		usage
 		exit 0
-		;;
-	f)
-		log_options+=("--follow")
 		;;
 	*)
 		usage
@@ -22,10 +17,11 @@ while getopts "hf" arg; do
 	esac
 done
 shift $((OPTIND - 1))
-if [[ $# -ne 1 ]]; then
+if [[ $# -eq 0 ]]; then
 	usage
 	exit 0
 fi
+
 ele_home=$(ele-config .cluster.home)
 ele_project=$(ele-config .cluster.project)
 if [[ -z $ele_home ]]; then
@@ -41,15 +37,9 @@ if [[ -z $ele_project ]]; then
 	exit 1
 fi
 
-readonly composeName=$1
-compose_file=$(/usr/lib/ele/get-path-compose.sh "$composeName")
-if [[ ! -f $compose_file ]]; then
-	echo "Compose file not exists for $composeName. ($compose_file)" 2>&1
-	exit 2
-fi
-
 options=()
 options+=(--project-name "$ele_project")
+
 # Add --env-file for each file found in $ele_home/env
 if [[ -d "$ele_home/env" ]]; then
 	while IFS= read -r envfile; do
@@ -57,10 +47,32 @@ if [[ -d "$ele_home/env" ]]; then
 	done < <(find "$ele_home/env" -type f)
 fi
 
-env_file=$(dirname "$compose_file")/.env
-if [[ -f $env_file ]]; then
-	options+=(--env-file="$env_file")
-fi
+up_options=()
 
-set -x
-docker compose -f "$compose_file" "${options[@]}" logs "${log_options[@]}"
+if [[ $# -eq 1 ]]; then
+	up_options+=(--attach-dependencies)
+else
+	echo "multiple compose files are specified, will not attach to dependencies." 2>&1
+fi
+for FILE in "$@"; do
+
+	compose_file=$(/usr/lib/ele/get-path-compose-init.sh "$FILE")
+
+	if [[ ! -f $compose_file ]]; then
+		echo "Compose file not exists for $FILE. ($compose_file)" 2>&1
+		exit 2
+	fi
+	env_file=$(dirname "$compose_file")/.env
+	compose_options=()
+	if [[ -f $env_file ]]; then
+		compose_options+=(--env-file="$env_file")
+	fi
+	(
+		set -x
+		docker compose "${options[@]}" "${compose_options[@]}" -f "$compose_file" up "${up_options[@]}"
+	)
+  if [[ $? -ne 0 ]]; then
+    echo "Failed to start $FILE" >&2
+    exit 1
+  fi
+done
